version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

